### ISSUE TITLE
add Twitter card markup

### ISSUE THREAD

**Issue by emilyweil** [cod1ng-earth/splicenft#45]
<img width="539" alt="TwitterCardValidatorForSplice" src="https://user-images.githubusercontent.com/34519397/137517907-5f9eae21-584e-4f15-a1db-ea497645859e.png">

**Comment by elmariachi111** [comment]
done ![image](https://user-images.githubusercontent.com/1344649/138092665-f035ccaa-4c5c-40ad-8f21-50d660379aa1.png)
